spring.application.name=ecom-app
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username:ecomapp
spring.datasource.password:ecomapp
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always